### ISSUE TITLE
No license is specified

### ISSUE THREAD

**Issue by werkshy** [simplicityitself/Mongo-Tomcat-Sessions#3]
I'm evaluating this project at the moment, the code is definitely clear and easy to get set up, thank you. Would it be possible to add a license file or header for this project. (The Apache license seems appropriate for a Tomcat plugin if you don't have a favourite license).

Much appreciated!

**Comment by dawsonsystems** [comment]
Headers added, also trimmed down the deps and removed the unecessary gmaven usage.

Cheers dude.

**Comment by werkshy** [comment]
That's great, thank you!
